"""complete_apollo_and_monid_schema_expansion

Revision ID: 72939ea8c1ae
Revises: e35b2f488f24
Create Date: 2026-08-17 11:04:02.819527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72939ea8c1ae'
down_revision: Union[str, Sequence[str], None] = 'e35b2f488f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_id', sa.UUID(), nullable=False),
    sa.Column('funding_event_id', sa.String(length=100), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('investors', sa.Text(), nullable=True),
    sa.Column('news_url', sa.String(length=500), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_funding_events_bank', 'funding_events', ['bank_id'], unique=False)
    op.create_index('idx_funding_events_type', 'funding_events', ['type'], unique=False)
    op.create_index(op.f('ix_funding_events_bank_id'), 'funding_events', ['bank_id'], unique=False)
    op.create_index(op.f('ix_funding_events_funding_event_id'), 'funding_events', ['funding_event_id'], unique=False)
    op.create_table('tool_execution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=True),
    sa.Column('bank_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('caller', sa.String(length=100), nullable=True),
    sa.Column('provider_http_status', sa.Integer(), nullable=True),
    sa.Column('original_query', sa.Text(), nullable=True),
    sa.Column('generated_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_queries', sa.Integer(), nullable=True),
    sa.Column('generated_query_count', sa.Integer(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('billed_units', sa.Integer(), nullable=True),
    sa.Column('full_content_token_count', sa.Integer(), nullable=True),
    sa.Column('overall_latency', sa.Float(), nullable=True),
    sa.Column('per_query_latency', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_type', sa.String(length=50), nullable=True),
    sa.Column('price_amount', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('price_currency', sa.String(length=20), nullable=True),
    sa.Column('price_notes', sa.Text(), nullable=True),
    sa.Column('tier_label', sa.String(length=100), nullable=True),
    sa.Column('unit_size', sa.String(length=50), nullable=True),
    sa.Column('pricing_condition', sa.String(length=255), nullable=True),
    sa.Column('reported_cost_value', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('reported_cost_currency', sa.String(length=20), nullable=True),
    sa.Column('reported_cost_unit', sa.String(length=50), nullable=True),
    sa.Column('retrieve_response_hint', sa.Text(), nullable=True),
    sa.Column('find_company_domain_hint', sa.Text(), nullable=True),
    sa.Column('inspect_schema_version', sa.String(length=50), nullable=True),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('raw_response_location', sa.String(length=500), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tool_exec_created', 'tool_execution_logs', ['created_at'], unique=False)
    op.create_index('idx_tool_exec_provider_status', 'tool_execution_logs', ['provider', 'status'], unique=False)
    op.create_index(op.f('ix_tool_execution_logs_bank_id'), 'tool_execution_logs', ['bank_id'], unique=False)
    op.create_index(op.f('ix_tool_execution_logs_provider'), 'tool_execution_logs', ['provider'], unique=False)
    op.create_index(op.f('ix_tool_execution_logs_run_id'), 'tool_execution_logs', ['run_id'], unique=True)
    op.create_index(op.f('ix_tool_execution_logs_status'), 'tool_execution_logs', ['status'], unique=False)
    op.create_table('bank_market_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_id', sa.UUID(), nullable=False),
    sa.Column('lob_id', sa.UUID(), nullable=True),
    sa.Column('customer_type', sa.String(length=100), nullable=True),
    sa.Column('client_segment', sa.String(length=100), nullable=True),
    sa.Column('organization_size', sa.String(length=100), nullable=True),
    sa.Column('customer_description', sa.Text(), nullable=True),
    sa.Column('market_name', sa.String(length=255), nullable=True),
    sa.Column('market_category', sa.String(length=100), nullable=True),
    sa.Column('geography', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('asset_class', sa.String(length=100), nullable=True),
    sa.Column('served_segment', sa.String(length=255), nullable=True),
    sa.Column('served_geography', sa.String(length=255), nullable=True),
    sa.Column('offering_relationship', sa.String(length=255), nullable=True),
    sa.Column('classification', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.String(length=50), nullable=True),
    sa.Column('evidence_url', sa.String(length=500), nullable=True),
    sa.Column('authoritative_source_flag', sa.Boolean(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lob_id'], ['bank_lobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_segments_bank', 'bank_market_segments', ['bank_id'], unique=False)
    op.create_index('idx_market_segments_client_type', 'bank_market_segments', ['customer_type', 'client_segment'], unique=False)
    op.create_index('idx_market_segments_lob', 'bank_market_segments', ['lob_id'], unique=False)
    op.create_index(op.f('ix_bank_market_segments_bank_id'), 'bank_market_segments', ['bank_id'], unique=False)
    op.create_index(op.f('ix_bank_market_segments_lob_id'), 'bank_market_segments', ['lob_id'], unique=False)
    op.create_index(op.f('ix_bank_market_segments_market_name'), 'bank_market_segments', ['market_name'], unique=False)
    op.create_table('bank_products_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_id', sa.UUID(), nullable=False),
    sa.Column('lob_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('product_parent_entity', sa.String(length=255), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('service_category', sa.String(length=100), nullable=True),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('delivery_function', sa.String(length=255), nullable=True),
    sa.Column('service_parent_entity', sa.String(length=255), nullable=True),
    sa.Column('function_name', sa.String(length=255), nullable=True),
    sa.Column('functional_responsibility', sa.Text(), nullable=True),
    sa.Column('supported_product_service', sa.String(length=255), nullable=True),
    sa.Column('function_parent_entity', sa.String(length=255), nullable=True),
    sa.Column('entity_to_product_relationship', sa.String(length=255), nullable=True),
    sa.Column('entity_to_service_relationship', sa.String(length=255), nullable=True),
    sa.Column('evidence_mapping_statement', sa.Text(), nullable=True),
    sa.Column('classification', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.String(length=50), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lob_id'], ['bank_lobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prod_serv_bank', 'bank_products_services', ['bank_id'], unique=False)
    op.create_index('idx_prod_serv_category', 'bank_products_services', ['product_category', 'service_category'], unique=False)
    op.create_index('idx_prod_serv_lob', 'bank_products_services', ['lob_id'], unique=False)
    op.create_index(op.f('ix_bank_products_services_bank_id'), 'bank_products_services', ['bank_id'], unique=False)
    op.create_index(op.f('ix_bank_products_services_lob_id'), 'bank_products_services', ['lob_id'], unique=False)
    op.create_index(op.f('ix_bank_products_services_product_name'), 'bank_products_services', ['product_name'], unique=False)
    op.create_index(op.f('ix_bank_products_services_service_name'), 'bank_products_services', ['service_name'], unique=False)
    op.create_table('bank_technology_initiatives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_id', sa.UUID(), nullable=False),
    sa.Column('lob_id', sa.UUID(), nullable=True),
    sa.Column('technology_name', sa.String(length=255), nullable=True),
    sa.Column('technology_category', sa.String(length=100), nullable=True),
    sa.Column('platform_vendor', sa.String(length=255), nullable=True),
    sa.Column('business_capability', sa.String(length=255), nullable=True),
    sa.Column('initiative_name', sa.String(length=255), nullable=True),
    sa.Column('initiative_description', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('timeline', sa.String(length=100), nullable=True),
    sa.Column('priority_name', sa.String(length=255), nullable=True),
    sa.Column('business_rationale', sa.Text(), nullable=True),
    sa.Column('related_pain_point', sa.Text(), nullable=True),
    sa.Column('related_technology', sa.Text(), nullable=True),
    sa.Column('business_owner', sa.String(length=255), nullable=True),
    sa.Column('technology_owner', sa.String(length=255), nullable=True),
    sa.Column('responsible_organization', sa.String(length=255), nullable=True),
    sa.Column('classification', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.String(length=50), nullable=True),
    sa.Column('evidence_date', sa.String(length=50), nullable=True),
    sa.Column('authoritative_source_flag', sa.Boolean(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lob_id'], ['bank_lobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tech_initiatives_bank', 'bank_technology_initiatives', ['bank_id'], unique=False)
    op.create_index('idx_tech_initiatives_lob', 'bank_technology_initiatives', ['lob_id'], unique=False)
    op.create_index('idx_tech_initiatives_tech_cat', 'bank_technology_initiatives', ['technology_category'], unique=False)
    op.create_index(op.f('ix_bank_technology_initiatives_bank_id'), 'bank_technology_initiatives', ['bank_id'], unique=False)
    op.create_index(op.f('ix_bank_technology_initiatives_initiative_name'), 'bank_technology_initiatives', ['initiative_name'], unique=False)
    op.create_index(op.f('ix_bank_technology_initiatives_lob_id'), 'bank_technology_initiatives', ['lob_id'], unique=False)
    op.create_index(op.f('ix_bank_technology_initiatives_technology_name'), 'bank_technology_initiatives', ['technology_name'], unique=False)
    op.create_table('data_source_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_id', sa.UUID(), nullable=True),
    sa.Column('lob_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('source_title', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('favicon', sa.String(length=1000), nullable=True),
    sa.Column('highlight', sa.Text(), nullable=True),
    sa.Column('full_content', sa.Text(), nullable=True),
    sa.Column('author_list', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('publication_timestamp', sa.String(length=50), nullable=True),
    sa.Column('last_crawled_timestamp', sa.String(length=50), nullable=True),
    sa.Column('official_domain_flag', sa.Boolean(), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('authority_level', sa.String(length=50), nullable=True),
    sa.Column('claim_identifier', sa.String(length=255), nullable=True),
    sa.Column('supported_field', sa.String(length=255), nullable=True),
    sa.Column('validation_result', sa.String(length=50), nullable=True),
    sa.Column('conflicting_source_flag', sa.Boolean(), nullable=True),
    sa.Column('canonical_url', sa.String(length=1000), nullable=True),
    sa.Column('source_hash', sa.String(length=255), nullable=True),
    sa.Column('duplicate_group_id', sa.String(length=100), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lob_id'], ['bank_lobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evidence_bank', 'data_source_evidence', ['bank_id'], unique=False)
    op.create_index('idx_evidence_domain', 'data_source_evidence', ['domain'], unique=False)
    op.create_index('idx_evidence_supported_field', 'data_source_evidence', ['supported_field'], unique=False)
    op.create_index(op.f('ix_data_source_evidence_bank_id'), 'data_source_evidence', ['bank_id'], unique=False)
    op.create_index(op.f('ix_data_source_evidence_contact_id'), 'data_source_evidence', ['contact_id'], unique=False)
    op.create_index(op.f('ix_data_source_evidence_domain'), 'data_source_evidence', ['domain'], unique=False)
    op.create_index(op.f('ix_data_source_evidence_lob_id'), 'data_source_evidence', ['lob_id'], unique=False)
    op.create_index(op.f('ix_data_source_evidence_source_hash'), 'data_source_evidence', ['source_hash'], unique=False)
    op.add_column('bank_lobs', sa.Column('parent_lob_id', sa.UUID(), nullable=True))
    op.add_column('bank_lobs', sa.Column('suborg_id', sa.String(length=100), nullable=True))
    op.add_column('bank_lobs', sa.Column('normalized_name', sa.String(length=255), nullable=True))
    op.add_column('bank_lobs', sa.Column('entity_type', sa.String(length=100), nullable=True))
    op.add_column('bank_lobs', sa.Column('hierarchy_path', sa.String(length=500), nullable=True))
    op.add_column('bank_lobs', sa.Column('hierarchy_depth', sa.Integer(), nullable=True))
    op.add_column('bank_lobs', sa.Column('estimated_num_employees', sa.Integer(), nullable=True))
    op.add_column('bank_lobs', sa.Column('website_url', sa.String(length=500), nullable=True))
    op.add_column('bank_lobs', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('bank_lobs', sa.Column('industries', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('bank_lobs', sa.Column('functions', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('bank_lobs', sa.Column('responsibilities', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('bank_lobs', sa.Column('business_head', sa.String(length=255), nullable=True))
    op.add_column('bank_lobs', sa.Column('tech_leader', sa.String(length=255), nullable=True))
    op.add_column('bank_lobs', sa.Column('tech_leader_title', sa.String(length=255), nullable=True))
    op.add_column('bank_lobs', sa.Column('confidence', sa.String(length=50), nullable=True))
    op.add_column('bank_lobs', sa.Column('key_platforms', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('bank_lobs', sa.Column('intelligence_notes', sa.Text(), nullable=True))
    op.add_column('bank_lobs', sa.Column('supporting_statement', sa.Text(), nullable=True))
    op.add_column('bank_lobs', sa.Column('classification', sa.String(length=100), nullable=True))
    op.add_column('bank_lobs', sa.Column('validation_status', sa.String(length=50), nullable=True))
    op.add_column('bank_lobs', sa.Column('evidence_count', sa.Integer(), nullable=True))
    op.add_column('bank_lobs', sa.Column('authoritative_source_flag', sa.Boolean(), nullable=True))
    op.add_column('bank_lobs', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bank_lobs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('bank_lobs', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('bank_lobs', 'type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index('idx_lob_industries', 'bank_lobs', ['industries'], unique=False, postgresql_using='gin')
    op.create_index('idx_lob_parent', 'bank_lobs', ['parent_lob_id'], unique=False)
    op.create_index('idx_lob_tech_stack', 'bank_lobs', ['tech_stack'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_bank_lobs_bank_id'), 'bank_lobs', ['bank_id'], unique=False)
    op.create_index(op.f('ix_bank_lobs_name'), 'bank_lobs', ['name'], unique=False)
    op.create_index(op.f('ix_bank_lobs_parent_lob_id'), 'bank_lobs', ['parent_lob_id'], unique=False)
    op.create_index(op.f('ix_bank_lobs_suborg_id'), 'bank_lobs', ['suborg_id'], unique=False)
    op.create_foreign_key(None, 'bank_lobs', 'bank_lobs', ['parent_lob_id'], ['id'], ondelete='SET NULL')
    op.add_column('banks', sa.Column('apollo_org_id', sa.String(length=100), nullable=True))
    op.add_column('banks', sa.Column('primary_domain', sa.String(length=255), nullable=True))
    op.add_column('banks', sa.Column('company_url', sa.String(length=500), nullable=True))
    op.add_column('banks', sa.Column('website_url', sa.String(length=500), nullable=True))
    op.add_column('banks', sa.Column('estimated_num_employees', sa.Integer(), nullable=True))
    op.add_column('banks', sa.Column('founded_year', sa.Integer(), nullable=True))
    op.add_column('banks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('banks', sa.Column('short_description', sa.Text(), nullable=True))
    op.add_column('banks', sa.Column('market_cap', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('organization_revenue', sa.BigInteger(), nullable=True))
    op.add_column('banks', sa.Column('organization_revenue_printed', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('annual_revenue', sa.BigInteger(), nullable=True))
    op.add_column('banks', sa.Column('annual_revenue_printed', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('total_funding', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('total_funding_printed', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('latest_funding_round_date', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('latest_funding_stage', sa.String(length=100), nullable=True))
    op.add_column('banks', sa.Column('funding_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('banks', sa.Column('num_suborganizations', sa.Integer(), nullable=True))
    op.add_column('banks', sa.Column('retail_location_count', sa.Integer(), nullable=True))
    op.add_column('banks', sa.Column('num_retail_locations', sa.Integer(), nullable=True))
    op.add_column('banks', sa.Column('num_languages', sa.Integer(), nullable=True))
    op.add_column('banks', sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('banks', sa.Column('snippets_loaded', sa.Boolean(), nullable=True))
    op.add_column('banks', sa.Column('owned_by_organization_id', sa.String(length=100), nullable=True))
    op.add_column('banks', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('primary_phone', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('banks', sa.Column('sanitized_phone', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('linkedin_uid', sa.String(length=100), nullable=True))
    op.add_column('banks', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('banks', sa.Column('twitter_url', sa.String(length=500), nullable=True))
    op.add_column('banks', sa.Column('facebook_url', sa.String(length=500), nullable=True))
    op.add_column('banks', sa.Column('angellist_url', sa.String(length=500), nullable=True))
    op.add_column('banks', sa.Column('crunchbase_url', sa.String(length=500), nullable=True))
    op.add_column('banks', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('banks', sa.Column('raw_address', sa.String(length=500), nullable=True))
    op.add_column('banks', sa.Column('street_address', sa.String(length=255), nullable=True))
    op.add_column('banks', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('banks', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('banks', sa.Column('postal_code', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('banks', sa.Column('industries', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('banks', sa.Column('secondary_industries', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('banks', sa.Column('sic_codes', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('banks', sa.Column('naics_codes', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('banks', sa.Column('industry_tag_id', sa.String(length=100), nullable=True))
    op.add_column('banks', sa.Column('industry_tag_hash', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('banks', sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('banks', sa.Column('technology_names', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('banks', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('banks', 'headquarters',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index(op.f('ix_banks_domain'), table_name='banks')
    op.create_index(op.f('ix_banks_domain'), 'banks', ['domain'], unique=False)
    op.create_index('idx_banks_domain', 'banks', ['domain'], unique=False)
    op.create_index('idx_banks_keywords', 'banks', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index('idx_banks_naics_codes', 'banks', ['naics_codes'], unique=False, postgresql_using='gin')
    op.create_index('idx_banks_primary_domain', 'banks', ['primary_domain'], unique=False)
    op.create_index('idx_banks_sic_codes', 'banks', ['sic_codes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_banks_apollo_org_id'), 'banks', ['apollo_org_id'], unique=False)
    op.create_index(op.f('ix_banks_company_url'), 'banks', ['company_url'], unique=False)
    op.create_index(op.f('ix_banks_primary_domain'), 'banks', ['primary_domain'], unique=False)
    op.add_column('contacts', sa.Column('node_id', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('bank_id', sa.UUID(), nullable=True))
    op.add_column('contacts', sa.Column('email_confidence', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('sub_lob_name', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('seniority_tier', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('target_persona_type', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('leadership_type', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('reports_to_name', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('reports_to_title', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('reports_to_path', sa.String(length=500), nullable=True))
    op.add_column('contacts', sa.Column('hierarchy_level', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('decision_authority', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('budget_authority', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('geography', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('start_date', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('tenure', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('current_role_validation_date', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('remit', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('responsibilities', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('classification', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('confidence', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('source_count', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('idx_contacts_score'), table_name='contacts')
    op.create_index('idx_contacts_score', 'contacts', ['lead_score'], unique=False, postgresql_ops={'lead_score': 'DESC'})
    op.create_index('idx_contacts_bank', 'contacts', ['bank_id'], unique=False)
    op.create_index('idx_contacts_node_id', 'contacts', ['node_id'], unique=False)
    op.create_index(op.f('ix_contacts_bank_id'), 'contacts', ['bank_id'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_lob_id'), 'contacts', ['lob_id'], unique=False)
    op.create_index(op.f('ix_contacts_node_id'), 'contacts', ['node_id'], unique=False)
    op.create_foreign_key(None, 'contacts', 'banks', ['bank_id'], ['id'], ondelete='CASCADE')
    op.add_column('org_hierarchy', sa.Column('reports_to_name', sa.String(length=255), nullable=True))
    op.add_column('org_hierarchy', sa.Column('reports_to_title', sa.String(length=255), nullable=True))
    op.add_column('org_hierarchy', sa.Column('parent_organization', sa.String(length=255), nullable=True))
    op.add_column('org_hierarchy', sa.Column('relationship_evidence', sa.Text(), nullable=True))
    op.add_column('org_hierarchy', sa.Column('budget_authority', sa.String(length=50), nullable=True))
    op.add_column('org_hierarchy', sa.Column('confidence', sa.String(length=50), nullable=True))
    op.add_column('org_hierarchy', sa.Column('evidence_count', sa.Integer(), nullable=True))
    op.add_column('org_hierarchy', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('org_hierarchy', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('idx_hierarchy_path'), table_name='org_hierarchy', postgresql_using='gist')
    op.add_column('personas', sa.Column('age_estimate', sa.Integer(), nullable=True))
    op.add_column('personas', sa.Column('tenure_months', sa.Integer(), nullable=True))
    op.add_column('personas', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('personas', sa.Column('education_degree', sa.String(length=255), nullable=True))
    op.add_column('personas', sa.Column('education_institution', sa.String(length=255), nullable=True))
    op.add_column('personas', sa.Column('education_grad_year', sa.Integer(), nullable=True))
    op.add_column('personas', sa.Column('prior_company', sa.String(length=255), nullable=True))
    op.add_column('personas', sa.Column('prior_title', sa.String(length=255), nullable=True))
    op.add_column('personas', sa.Column('prior_duration_months', sa.Integer(), nullable=True))
    op.add_column('personas', sa.Column('intent_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('personas', sa.Column('is_scraped', sa.Boolean(), nullable=True))
    op.add_column('personas', sa.Column('is_ai_generated', sa.Boolean(), nullable=True))
    op.add_column('personas', sa.Column('scraping_source', sa.String(length=100), nullable=True))
    op.add_column('personas', sa.Column('scraping_status', sa.String(length=50), nullable=True))
    op.add_column('personas', sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('personas', sa.Column('engagement_rate', sa.String(length=50), nullable=True))
    op.add_column('personas', sa.Column('communication_style', sa.String(length=100), nullable=True))
    op.add_column('personas', sa.Column('professional_interests', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('personas', sa.Column('social_platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('personas', sa.Column('recent_scraped_posts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('personas', sa.Column('value_proposition', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('objections', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('personas', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('personas', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index('idx_personas_personal', 'personas', ['personal_touch'], unique=False, postgresql_using='gin', postgresql_ops={'personal_touch': 'jsonb_path_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_personas_personal', table_name='personas', postgresql_using='gin', postgresql_ops={'personal_touch': 'jsonb_path_ops'})
    op.drop_column('personas', 'updated_at')
    op.drop_column('personas', 'raw_data')
    op.drop_column('personas', 'objections')
    op.drop_column('personas', 'value_proposition')
    op.drop_column('personas', 'recent_scraped_posts')
    op.drop_column('personas', 'social_platforms')
    op.drop_column('personas', 'professional_interests')
    op.drop_column('personas', 'communication_style')
    op.drop_column('personas', 'engagement_rate')
    op.drop_column('personas', 'scraped_at')
    op.drop_column('personas', 'scraping_status')
    op.drop_column('personas', 'scraping_source')
    op.drop_column('personas', 'is_ai_generated')
    op.drop_column('personas', 'is_scraped')
    op.drop_column('personas', 'intent_signals')
    op.drop_column('personas', 'prior_duration_months')
    op.drop_column('personas', 'prior_title')
    op.drop_column('personas', 'prior_company')
    op.drop_column('personas', 'education_grad_year')
    op.drop_column('personas', 'education_institution')
    op.drop_column('personas', 'education_degree')
    op.drop_column('personas', 'location')
    op.drop_column('personas', 'tenure_months')
    op.drop_column('personas', 'age_estimate')
    op.create_index(op.f('idx_hierarchy_path'), 'org_hierarchy', ['reports_to_path'], unique=False, postgresql_using='gist')
    op.drop_column('org_hierarchy', 'updated_at')
    op.drop_column('org_hierarchy', 'raw_data')
    op.drop_column('org_hierarchy', 'evidence_count')
    op.drop_column('org_hierarchy', 'confidence')
    op.drop_column('org_hierarchy', 'budget_authority')
    op.drop_column('org_hierarchy', 'relationship_evidence')
    op.drop_column('org_hierarchy', 'parent_organization')
    op.drop_column('org_hierarchy', 'reports_to_title')
    op.drop_column('org_hierarchy', 'reports_to_name')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_index(op.f('ix_contacts_node_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_lob_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_bank_id'), table_name='contacts')
    op.drop_index('idx_contacts_node_id', table_name='contacts')
    op.drop_index('idx_contacts_bank', table_name='contacts')
    op.drop_index('idx_contacts_score', table_name='contacts', postgresql_ops={'lead_score': 'DESC'})
    op.create_index(op.f('idx_contacts_score'), 'contacts', [sa.literal_column('lead_score DESC')], unique=False)
    op.drop_column('contacts', 'raw_data')
    op.drop_column('contacts', 'source_count')
    op.drop_column('contacts', 'confidence')
    op.drop_column('contacts', 'classification')
    op.drop_column('contacts', 'responsibilities')
    op.drop_column('contacts', 'remit')
    op.drop_column('contacts', 'current_role_validation_date')
    op.drop_column('contacts', 'tenure')
    op.drop_column('contacts', 'start_date')
    op.drop_column('contacts', 'geography')
    op.drop_column('contacts', 'budget_authority')
    op.drop_column('contacts', 'decision_authority')
    op.drop_column('contacts', 'hierarchy_level')
    op.drop_column('contacts', 'reports_to_path')
    op.drop_column('contacts', 'reports_to_title')
    op.drop_column('contacts', 'reports_to_name')
    op.drop_column('contacts', 'leadership_type')
    op.drop_column('contacts', 'target_persona_type')
    op.drop_column('contacts', 'seniority_tier')
    op.drop_column('contacts', 'sub_lob_name')
    op.drop_column('contacts', 'email_confidence')
    op.drop_column('contacts', 'bank_id')
    op.drop_column('contacts', 'node_id')
    op.drop_index(op.f('ix_banks_primary_domain'), table_name='banks')
    op.drop_index(op.f('ix_banks_company_url'), table_name='banks')
    op.drop_index(op.f('ix_banks_apollo_org_id'), table_name='banks')
    op.drop_index('idx_banks_sic_codes', table_name='banks', postgresql_using='gin')
    op.drop_index('idx_banks_primary_domain', table_name='banks')
    op.drop_index('idx_banks_naics_codes', table_name='banks', postgresql_using='gin')
    op.drop_index('idx_banks_keywords', table_name='banks', postgresql_using='gin')
    op.drop_index('idx_banks_domain', table_name='banks')
    op.drop_index(op.f('ix_banks_domain'), table_name='banks')
    op.create_index(op.f('ix_banks_domain'), 'banks', ['domain'], unique=True)
    op.alter_column('banks', 'headquarters',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('banks', 'raw_data')
    op.drop_column('banks', 'technology_names')
    op.drop_column('banks', 'keywords')
    op.drop_column('banks', 'industry_tag_hash')
    op.drop_column('banks', 'industry_tag_id')
    op.drop_column('banks', 'naics_codes')
    op.drop_column('banks', 'sic_codes')
    op.drop_column('banks', 'secondary_industries')
    op.drop_column('banks', 'industries')
    op.drop_column('banks', 'country')
    op.drop_column('banks', 'postal_code')
    op.drop_column('banks', 'state')
    op.drop_column('banks', 'city')
    op.drop_column('banks', 'street_address')
    op.drop_column('banks', 'raw_address')
    op.drop_column('banks', 'logo_url')
    op.drop_column('banks', 'crunchbase_url')
    op.drop_column('banks', 'angellist_url')
    op.drop_column('banks', 'facebook_url')
    op.drop_column('banks', 'twitter_url')
    op.drop_column('banks', 'linkedin_url')
    op.drop_column('banks', 'linkedin_uid')
    op.drop_column('banks', 'sanitized_phone')
    op.drop_column('banks', 'primary_phone')
    op.drop_column('banks', 'phone')
    op.drop_column('banks', 'owned_by_organization_id')
    op.drop_column('banks', 'snippets_loaded')
    op.drop_column('banks', 'languages')
    op.drop_column('banks', 'num_languages')
    op.drop_column('banks', 'num_retail_locations')
    op.drop_column('banks', 'retail_location_count')
    op.drop_column('banks', 'num_suborganizations')
    op.drop_column('banks', 'funding_events')
    op.drop_column('banks', 'latest_funding_stage')
    op.drop_column('banks', 'latest_funding_round_date')
    op.drop_column('banks', 'total_funding_printed')
    op.drop_column('banks', 'total_funding')
    op.drop_column('banks', 'annual_revenue_printed')
    op.drop_column('banks', 'annual_revenue')
    op.drop_column('banks', 'organization_revenue_printed')
    op.drop_column('banks', 'organization_revenue')
    op.drop_column('banks', 'market_cap')
    op.drop_column('banks', 'short_description')
    op.drop_column('banks', 'description')
    op.drop_column('banks', 'founded_year')
    op.drop_column('banks', 'estimated_num_employees')
    op.drop_column('banks', 'website_url')
    op.drop_column('banks', 'company_url')
    op.drop_column('banks', 'primary_domain')
    op.drop_column('banks', 'apollo_org_id')
    op.drop_constraint(None, 'bank_lobs', type_='foreignkey')
    op.drop_index(op.f('ix_bank_lobs_suborg_id'), table_name='bank_lobs')
    op.drop_index(op.f('ix_bank_lobs_parent_lob_id'), table_name='bank_lobs')
    op.drop_index(op.f('ix_bank_lobs_name'), table_name='bank_lobs')
    op.drop_index(op.f('ix_bank_lobs_bank_id'), table_name='bank_lobs')
    op.drop_index('idx_lob_tech_stack', table_name='bank_lobs', postgresql_using='gin')
    op.drop_index('idx_lob_parent', table_name='bank_lobs')
    op.drop_index('idx_lob_industries', table_name='bank_lobs', postgresql_using='gin')
    op.alter_column('bank_lobs', 'type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('bank_lobs', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('bank_lobs', 'updated_at')
    op.drop_column('bank_lobs', 'raw_data')
    op.drop_column('bank_lobs', 'authoritative_source_flag')
    op.drop_column('bank_lobs', 'evidence_count')
    op.drop_column('bank_lobs', 'validation_status')
    op.drop_column('bank_lobs', 'classification')
    op.drop_column('bank_lobs', 'supporting_statement')
    op.drop_column('bank_lobs', 'intelligence_notes')
    op.drop_column('bank_lobs', 'key_platforms')
    op.drop_column('bank_lobs', 'confidence')
    op.drop_column('bank_lobs', 'tech_leader_title')
    op.drop_column('bank_lobs', 'tech_leader')
    op.drop_column('bank_lobs', 'business_head')
    op.drop_column('bank_lobs', 'responsibilities')
    op.drop_column('bank_lobs', 'functions')
    op.drop_column('bank_lobs', 'industries')
    op.drop_column('bank_lobs', 'country')
    op.drop_column('bank_lobs', 'website_url')
    op.drop_column('bank_lobs', 'estimated_num_employees')
    op.drop_column('bank_lobs', 'hierarchy_depth')
    op.drop_column('bank_lobs', 'hierarchy_path')
    op.drop_column('bank_lobs', 'entity_type')
    op.drop_column('bank_lobs', 'normalized_name')
    op.drop_column('bank_lobs', 'suborg_id')
    op.drop_column('bank_lobs', 'parent_lob_id')
    op.drop_index(op.f('ix_data_source_evidence_source_hash'), table_name='data_source_evidence')
    op.drop_index(op.f('ix_data_source_evidence_lob_id'), table_name='data_source_evidence')
    op.drop_index(op.f('ix_data_source_evidence_domain'), table_name='data_source_evidence')
    op.drop_index(op.f('ix_data_source_evidence_contact_id'), table_name='data_source_evidence')
    op.drop_index(op.f('ix_data_source_evidence_bank_id'), table_name='data_source_evidence')
    op.drop_index('idx_evidence_supported_field', table_name='data_source_evidence')
    op.drop_index('idx_evidence_domain', table_name='data_source_evidence')
    op.drop_index('idx_evidence_bank', table_name='data_source_evidence')
    op.drop_table('data_source_evidence')
    op.drop_index(op.f('ix_bank_technology_initiatives_technology_name'), table_name='bank_technology_initiatives')
    op.drop_index(op.f('ix_bank_technology_initiatives_lob_id'), table_name='bank_technology_initiatives')
    op.drop_index(op.f('ix_bank_technology_initiatives_initiative_name'), table_name='bank_technology_initiatives')
    op.drop_index(op.f('ix_bank_technology_initiatives_bank_id'), table_name='bank_technology_initiatives')
    op.drop_index('idx_tech_initiatives_tech_cat', table_name='bank_technology_initiatives')
    op.drop_index('idx_tech_initiatives_lob', table_name='bank_technology_initiatives')
    op.drop_index('idx_tech_initiatives_bank', table_name='bank_technology_initiatives')
    op.drop_table('bank_technology_initiatives')
    op.drop_index(op.f('ix_bank_products_services_service_name'), table_name='bank_products_services')
    op.drop_index(op.f('ix_bank_products_services_product_name'), table_name='bank_products_services')
    op.drop_index(op.f('ix_bank_products_services_lob_id'), table_name='bank_products_services')
    op.drop_index(op.f('ix_bank_products_services_bank_id'), table_name='bank_products_services')
    op.drop_index('idx_prod_serv_lob', table_name='bank_products_services')
    op.drop_index('idx_prod_serv_category', table_name='bank_products_services')
    op.drop_index('idx_prod_serv_bank', table_name='bank_products_services')
    op.drop_table('bank_products_services')
    op.drop_index(op.f('ix_bank_market_segments_market_name'), table_name='bank_market_segments')
    op.drop_index(op.f('ix_bank_market_segments_lob_id'), table_name='bank_market_segments')
    op.drop_index(op.f('ix_bank_market_segments_bank_id'), table_name='bank_market_segments')
    op.drop_index('idx_market_segments_lob', table_name='bank_market_segments')
    op.drop_index('idx_market_segments_client_type', table_name='bank_market_segments')
    op.drop_index('idx_market_segments_bank', table_name='bank_market_segments')
    op.drop_table('bank_market_segments')
    op.drop_index(op.f('ix_tool_execution_logs_status'), table_name='tool_execution_logs')
    op.drop_index(op.f('ix_tool_execution_logs_run_id'), table_name='tool_execution_logs')
    op.drop_index(op.f('ix_tool_execution_logs_provider'), table_name='tool_execution_logs')
    op.drop_index(op.f('ix_tool_execution_logs_bank_id'), table_name='tool_execution_logs')
    op.drop_index('idx_tool_exec_provider_status', table_name='tool_execution_logs')
    op.drop_index('idx_tool_exec_created', table_name='tool_execution_logs')
    op.drop_table('tool_execution_logs')
    op.drop_index(op.f('ix_funding_events_funding_event_id'), table_name='funding_events')
    op.drop_index(op.f('ix_funding_events_bank_id'), table_name='funding_events')
    op.drop_index('idx_funding_events_type', table_name='funding_events')
    op.drop_index('idx_funding_events_bank', table_name='funding_events')
    op.drop_table('funding_events')
    # ### end Alembic commands ###
