"""create_account_technologies_and_taxonomies_tables

Revision ID: 96a49b21043c
Revises: f4cd119c6dbd
Create Date: 2026-08-17 22:01:11.275114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96a49b21043c'
down_revision: Union[str, Sequence[str], None] = 'f4cd119c6dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_taxonomies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('code_type', sa.String(length=50), nullable=False),
    sa.Column('code_value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_account_tax_type_val', 'account_taxonomies', ['account_id', 'code_type', 'code_value'], unique=False)
    op.create_index(op.f('ix_account_taxonomies_account_id'), 'account_taxonomies', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_taxonomies_code_type'), 'account_taxonomies', ['code_type'], unique=False)
    op.create_index(op.f('ix_account_taxonomies_code_value'), 'account_taxonomies', ['code_value'], unique=False)
    op.create_table('account_technologies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('technology_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_account_tech_category', 'account_technologies', ['category'], unique=False)
    op.create_index('idx_account_tech_name', 'account_technologies', ['account_id', 'technology_name'], unique=False)
    op.create_index(op.f('ix_account_technologies_account_id'), 'account_technologies', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_technologies_technology_name'), 'account_technologies', ['technology_name'], unique=False)
    op.drop_index(op.f('idx_bank_lobs_hierarchy_path'), table_name='account_lobs')
    op.drop_index(op.f('idx_bank_lobs_name'), table_name='account_lobs')
    op.drop_index(op.f('ix_bank_lobs_bank_id'), table_name='account_lobs')
    op.drop_index(op.f('ix_bank_lobs_name'), table_name='account_lobs')
    op.drop_index(op.f('ix_bank_lobs_parent_lob_id'), table_name='account_lobs')
    op.drop_index(op.f('ix_bank_lobs_suborg_id'), table_name='account_lobs')
    op.create_index('idx_account_lobs_hierarchy_path', 'account_lobs', ['hierarchy_path'], unique=False)
    op.create_index('idx_account_lobs_name', 'account_lobs', ['name'], unique=False)
    op.create_index(op.f('ix_account_lobs_account_id'), 'account_lobs', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_lobs_name'), 'account_lobs', ['name'], unique=False)
    op.create_index(op.f('ix_account_lobs_parent_lob_id'), 'account_lobs', ['parent_lob_id'], unique=False)
    op.create_index(op.f('ix_account_lobs_suborg_id'), 'account_lobs', ['suborg_id'], unique=False)
    op.drop_index(op.f('ix_bank_market_segments_bank_id'), table_name='account_market_segments')
    op.drop_index(op.f('ix_bank_market_segments_lob_id'), table_name='account_market_segments')
    op.create_index(op.f('ix_account_market_segments_account_id'), 'account_market_segments', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_market_segments_lob_id'), 'account_market_segments', ['lob_id'], unique=False)
    op.drop_index(op.f('ix_bank_products_services_bank_id'), table_name='account_products_services')
    op.drop_index(op.f('ix_bank_products_services_lob_id'), table_name='account_products_services')
    op.create_index(op.f('ix_account_products_services_account_id'), 'account_products_services', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_products_services_lob_id'), 'account_products_services', ['lob_id'], unique=False)
    op.drop_index(op.f('ix_bank_technology_initiatives_bank_id'), table_name='account_technology_initiatives')
    op.drop_index(op.f('ix_bank_technology_initiatives_lob_id'), table_name='account_technology_initiatives')
    op.create_index(op.f('ix_account_technology_initiatives_account_id'), 'account_technology_initiatives', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_technology_initiatives_lob_id'), 'account_technology_initiatives', ['lob_id'], unique=False)
    op.drop_index(op.f('idx_banks_domain'), table_name='accounts')
    op.drop_index(op.f('idx_banks_keywords'), table_name='accounts', postgresql_using='gin')
    op.drop_index(op.f('idx_banks_naics_codes'), table_name='accounts', postgresql_using='gin')
    op.drop_index(op.f('idx_banks_name'), table_name='accounts')
    op.drop_index(op.f('idx_banks_sic_codes'), table_name='accounts', postgresql_using='gin')
    op.drop_index(op.f('ix_banks_apollo_org_id'), table_name='accounts')
    op.drop_index(op.f('ix_banks_domain'), table_name='accounts')
    op.drop_index(op.f('ix_banks_industry'), table_name='accounts')
    op.drop_index(op.f('ix_banks_name'), table_name='accounts')
    op.drop_index(op.f('ix_banks_primary_domain'), table_name='accounts')
    op.create_index('idx_accounts_domain', 'accounts', ['domain'], unique=False)
    op.create_index('idx_accounts_keywords', 'accounts', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index('idx_accounts_naics_codes', 'accounts', ['naics_codes'], unique=False, postgresql_using='gin')
    op.create_index('idx_accounts_name', 'accounts', ['name'], unique=False)
    op.create_index('idx_accounts_sic_codes', 'accounts', ['sic_codes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_accounts_apollo_org_id'), 'accounts', ['apollo_org_id'], unique=False)
    op.create_index(op.f('ix_accounts_domain'), 'accounts', ['domain'], unique=False)
    op.create_index(op.f('ix_accounts_industry'), 'accounts', ['industry'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_index(op.f('ix_accounts_primary_domain'), 'accounts', ['primary_domain'], unique=False)
    op.alter_column('contacts', 'buyer_roles',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("ARRAY['Key Decision Maker'::text]"))
    op.drop_index(op.f('ix_contacts_bank_id'), table_name='contacts')
    op.create_index(op.f('ix_contacts_account_id'), 'contacts', ['account_id'], unique=False)
    op.drop_index(op.f('ix_data_source_evidence_bank_id'), table_name='data_source_evidence')
    op.create_index(op.f('ix_data_source_evidence_account_id'), 'data_source_evidence', ['account_id'], unique=False)
    op.drop_constraint(op.f('data_source_evidence_lob_id_fkey'), 'data_source_evidence', type_='foreignkey')
    op.create_foreign_key(None, 'data_source_evidence', 'account_lobs', ['lob_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_funding_events_bank_id'), table_name='funding_events')
    op.create_index(op.f('ix_funding_events_account_id'), 'funding_events', ['account_id'], unique=False)
    op.alter_column('personas', 'skills',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_index(op.f('idx_pipeline_runs_bank_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_bank_id'), table_name='pipeline_runs')
    op.create_index('idx_pipeline_runs_account_status', 'pipeline_runs', ['account_id', 'status'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_account_id'), 'pipeline_runs', ['account_id'], unique=False)
    op.drop_index(op.f('idx_trigger_signals_bank_priority'), table_name='sales_trigger_signals')
    op.drop_index(op.f('ix_sales_trigger_signals_bank_id'), table_name='sales_trigger_signals')
    op.create_index('idx_trigger_signals_account_priority', 'sales_trigger_signals', ['account_id', 'priority'], unique=False)
    op.create_index(op.f('ix_sales_trigger_signals_account_id'), 'sales_trigger_signals', ['account_id'], unique=False)
    op.drop_constraint(op.f('sales_trigger_signals_lob_id_fkey'), 'sales_trigger_signals', type_='foreignkey')
    op.create_foreign_key(None, 'sales_trigger_signals', 'account_lobs', ['lob_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_social_bank_platform'), table_name='social_intelligence')
    op.drop_index(op.f('ix_social_intelligence_bank_id'), table_name='social_intelligence')
    op.create_index('idx_social_account_platform', 'social_intelligence', ['account_id', 'platform'], unique=False)
    op.create_index(op.f('ix_social_intelligence_account_id'), 'social_intelligence', ['account_id'], unique=False)
    op.drop_index(op.f('ix_tool_execution_logs_bank_id'), table_name='tool_execution_logs')
    op.create_index(op.f('ix_tool_execution_logs_account_id'), 'tool_execution_logs', ['account_id'], unique=False)
    op.drop_constraint(op.f('tool_execution_logs_account_id_fkey'), 'tool_execution_logs', type_='foreignkey')
    op.create_foreign_key(None, 'tool_execution_logs', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tool_execution_logs', type_='foreignkey')
    op.create_foreign_key(op.f('tool_execution_logs_account_id_fkey'), 'tool_execution_logs', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tool_execution_logs_account_id'), table_name='tool_execution_logs')
    op.create_index(op.f('ix_tool_execution_logs_bank_id'), 'tool_execution_logs', ['account_id'], unique=False)
    op.drop_index(op.f('ix_social_intelligence_account_id'), table_name='social_intelligence')
    op.drop_index('idx_social_account_platform', table_name='social_intelligence')
    op.create_index(op.f('ix_social_intelligence_bank_id'), 'social_intelligence', ['account_id'], unique=False)
    op.create_index(op.f('idx_social_bank_platform'), 'social_intelligence', ['account_id', 'platform'], unique=False)
    op.drop_constraint(None, 'sales_trigger_signals', type_='foreignkey')
    op.create_foreign_key(op.f('sales_trigger_signals_lob_id_fkey'), 'sales_trigger_signals', 'account_lobs', ['lob_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sales_trigger_signals_account_id'), table_name='sales_trigger_signals')
    op.drop_index('idx_trigger_signals_account_priority', table_name='sales_trigger_signals')
    op.create_index(op.f('ix_sales_trigger_signals_bank_id'), 'sales_trigger_signals', ['account_id'], unique=False)
    op.create_index(op.f('idx_trigger_signals_bank_priority'), 'sales_trigger_signals', ['account_id', 'priority'], unique=False)
    op.drop_index(op.f('ix_pipeline_runs_account_id'), table_name='pipeline_runs')
    op.drop_index('idx_pipeline_runs_account_status', table_name='pipeline_runs')
    op.create_index(op.f('ix_pipeline_runs_bank_id'), 'pipeline_runs', ['account_id'], unique=False)
    op.create_index(op.f('idx_pipeline_runs_bank_status'), 'pipeline_runs', ['account_id', 'status'], unique=False)
    op.alter_column('personas', 'skills',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_index(op.f('ix_funding_events_account_id'), table_name='funding_events')
    op.create_index(op.f('ix_funding_events_bank_id'), 'funding_events', ['account_id'], unique=False)
    op.drop_constraint(None, 'data_source_evidence', type_='foreignkey')
    op.create_foreign_key(op.f('data_source_evidence_lob_id_fkey'), 'data_source_evidence', 'account_lobs', ['lob_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_data_source_evidence_account_id'), table_name='data_source_evidence')
    op.create_index(op.f('ix_data_source_evidence_bank_id'), 'data_source_evidence', ['account_id'], unique=False)
    op.drop_index(op.f('ix_contacts_account_id'), table_name='contacts')
    op.create_index(op.f('ix_contacts_bank_id'), 'contacts', ['account_id'], unique=False)
    op.alter_column('contacts', 'buyer_roles',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("ARRAY['Key Decision Maker'::text]"))
    op.drop_index(op.f('ix_accounts_primary_domain'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_industry'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_domain'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_apollo_org_id'), table_name='accounts')
    op.drop_index('idx_accounts_sic_codes', table_name='accounts', postgresql_using='gin')
    op.drop_index('idx_accounts_name', table_name='accounts')
    op.drop_index('idx_accounts_naics_codes', table_name='accounts', postgresql_using='gin')
    op.drop_index('idx_accounts_keywords', table_name='accounts', postgresql_using='gin')
    op.drop_index('idx_accounts_domain', table_name='accounts')
    op.create_index(op.f('ix_banks_primary_domain'), 'accounts', ['primary_domain'], unique=False)
    op.create_index(op.f('ix_banks_name'), 'accounts', ['name'], unique=False)
    op.create_index(op.f('ix_banks_industry'), 'accounts', ['industry'], unique=False)
    op.create_index(op.f('ix_banks_domain'), 'accounts', ['domain'], unique=False)
    op.create_index(op.f('ix_banks_apollo_org_id'), 'accounts', ['apollo_org_id'], unique=False)
    op.create_index(op.f('idx_banks_sic_codes'), 'accounts', ['sic_codes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_banks_name'), 'accounts', ['name'], unique=False)
    op.create_index(op.f('idx_banks_naics_codes'), 'accounts', ['naics_codes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_banks_keywords'), 'accounts', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_banks_domain'), 'accounts', ['domain'], unique=False)
    op.drop_index(op.f('ix_account_technology_initiatives_lob_id'), table_name='account_technology_initiatives')
    op.drop_index(op.f('ix_account_technology_initiatives_account_id'), table_name='account_technology_initiatives')
    op.create_index(op.f('ix_bank_technology_initiatives_lob_id'), 'account_technology_initiatives', ['lob_id'], unique=False)
    op.create_index(op.f('ix_bank_technology_initiatives_bank_id'), 'account_technology_initiatives', ['account_id'], unique=False)
    op.drop_index(op.f('ix_account_products_services_lob_id'), table_name='account_products_services')
    op.drop_index(op.f('ix_account_products_services_account_id'), table_name='account_products_services')
    op.create_index(op.f('ix_bank_products_services_lob_id'), 'account_products_services', ['lob_id'], unique=False)
    op.create_index(op.f('ix_bank_products_services_bank_id'), 'account_products_services', ['account_id'], unique=False)
    op.drop_index(op.f('ix_account_market_segments_lob_id'), table_name='account_market_segments')
    op.drop_index(op.f('ix_account_market_segments_account_id'), table_name='account_market_segments')
    op.create_index(op.f('ix_bank_market_segments_lob_id'), 'account_market_segments', ['lob_id'], unique=False)
    op.create_index(op.f('ix_bank_market_segments_bank_id'), 'account_market_segments', ['account_id'], unique=False)
    op.drop_index(op.f('ix_account_lobs_suborg_id'), table_name='account_lobs')
    op.drop_index(op.f('ix_account_lobs_parent_lob_id'), table_name='account_lobs')
    op.drop_index(op.f('ix_account_lobs_name'), table_name='account_lobs')
    op.drop_index(op.f('ix_account_lobs_account_id'), table_name='account_lobs')
    op.drop_index('idx_account_lobs_name', table_name='account_lobs')
    op.drop_index('idx_account_lobs_hierarchy_path', table_name='account_lobs')
    op.create_index(op.f('ix_bank_lobs_suborg_id'), 'account_lobs', ['suborg_id'], unique=False)
    op.create_index(op.f('ix_bank_lobs_parent_lob_id'), 'account_lobs', ['parent_lob_id'], unique=False)
    op.create_index(op.f('ix_bank_lobs_name'), 'account_lobs', ['name'], unique=False)
    op.create_index(op.f('ix_bank_lobs_bank_id'), 'account_lobs', ['account_id'], unique=False)
    op.create_index(op.f('idx_bank_lobs_name'), 'account_lobs', ['name'], unique=False)
    op.create_index(op.f('idx_bank_lobs_hierarchy_path'), 'account_lobs', ['hierarchy_path'], unique=False)
    op.drop_index(op.f('ix_account_technologies_technology_name'), table_name='account_technologies')
    op.drop_index(op.f('ix_account_technologies_account_id'), table_name='account_technologies')
    op.drop_index('idx_account_tech_name', table_name='account_technologies')
    op.drop_index('idx_account_tech_category', table_name='account_technologies')
    op.drop_table('account_technologies')
    op.drop_index(op.f('ix_account_taxonomies_code_value'), table_name='account_taxonomies')
    op.drop_index(op.f('ix_account_taxonomies_code_type'), table_name='account_taxonomies')
    op.drop_index(op.f('ix_account_taxonomies_account_id'), table_name='account_taxonomies')
    op.drop_index('idx_account_tax_type_val', table_name='account_taxonomies')
    op.drop_table('account_taxonomies')
    # ### end Alembic commands ###
