"""add_all_371_data_points_across_models

Revision ID: b43080540cfb
Revises: 2c724ad5d6ed
Create Date: 2026-08-17 12:06:28.942134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b43080540cfb'
down_revision: Union[str, Sequence[str], None] = '2c724ad5d6ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_lobs', sa.Column('entity_name', sa.String(length=255), nullable=True))
    op.add_column('bank_lobs', sa.Column('normalized_name', sa.String(length=255), nullable=True))
    op.add_column('bank_lobs', sa.Column('business_unit_name', sa.String(length=255), nullable=True))
    op.add_column('bank_lobs', sa.Column('node_name', sa.String(length=255), nullable=True))
    op.add_column('bank_lobs', sa.Column('node_type', sa.String(length=100), nullable=True))
    op.add_column('bank_lobs', sa.Column('parent_entity', sa.String(length=255), nullable=True))
    op.add_column('bank_lobs', sa.Column('child_entity', sa.String(length=255), nullable=True))
    op.add_column('bank_lobs', sa.Column('child_node', sa.String(length=255), nullable=True))
    op.add_column('bank_lobs', sa.Column('parent_child_relationship', sa.String(length=255), nullable=True))
    op.add_column('bank_lobs', sa.Column('relationship_type', sa.String(length=100), nullable=True))
    op.add_column('bank_lobs', sa.Column('relationship_description', sa.Text(), nullable=True))
    op.add_column('bank_lobs', sa.Column('estimated_num_employees', sa.Integer(), nullable=True))
    op.add_column('bank_lobs', sa.Column('industries', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('bank_lobs', sa.Column('functions', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('bank_lobs', sa.Column('responsibilities', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('bank_lobs', sa.Column('division_leader', sa.String(length=255), nullable=True))
    op.add_column('bank_lobs', sa.Column('confidence_level', sa.String(length=50), nullable=True))
    op.add_column('bank_lobs', sa.Column('key_platforms', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('bank_lobs', sa.Column('short_description', sa.Text(), nullable=True))
    op.add_column('bank_lobs', sa.Column('detailed_description', sa.Text(), nullable=True))
    op.add_column('bank_lobs', sa.Column('supporting_statement', sa.Text(), nullable=True))
    op.add_column('bank_lobs', sa.Column('classification', sa.String(length=100), nullable=True))
    op.add_column('bank_lobs', sa.Column('classification_type', sa.String(length=100), nullable=True))
    op.add_column('bank_lobs', sa.Column('validation_status', sa.String(length=50), nullable=True))
    op.add_column('bank_lobs', sa.Column('evidence_count', sa.Integer(), nullable=True))
    op.add_column('bank_lobs', sa.Column('authoritative_source_flag', sa.Boolean(), nullable=True))
    op.add_column('bank_lobs', sa.Column('source_title', sa.String(length=500), nullable=True))
    op.add_column('bank_lobs', sa.Column('source_url', sa.String(length=1000), nullable=True))
    op.add_column('bank_lobs', sa.Column('highlighted_excerpt', sa.Text(), nullable=True))
    op.add_column('bank_lobs', sa.Column('excerpt', sa.Text(), nullable=True))
    op.add_column('bank_lobs', sa.Column('full_content', sa.Text(), nullable=True))
    op.add_column('bank_lobs', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('bank_lobs', sa.Column('publication_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bank_lobs', sa.Column('crawl_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bank_lobs', sa.Column('published_time', sa.String(length=50), nullable=True))
    op.add_column('bank_lobs', sa.Column('last_crawled_time', sa.String(length=50), nullable=True))
    op.drop_index(op.f('idx_lob_bank_parent'), table_name='bank_lobs')
    op.create_index('idx_bank_lobs_hierarchy_path', 'bank_lobs', ['hierarchy_path'], unique=False)
    op.create_index('idx_bank_lobs_name', 'bank_lobs', ['name'], unique=False)
    op.add_column('bank_market_segments', sa.Column('parent_lob_sub_lob', sa.String(length=255), nullable=True))
    op.alter_column('bank_market_segments', 'lob_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('bank_market_segments', 'served_segment',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('bank_market_segments', 'served_geography',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('bank_market_segments', 'evidence_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_index(op.f('idx_market_segments_bank'), table_name='bank_market_segments')
    op.drop_index(op.f('idx_market_segments_client_type'), table_name='bank_market_segments')
    op.drop_index(op.f('idx_market_segments_lob'), table_name='bank_market_segments')
    op.drop_index(op.f('ix_bank_market_segments_market_name'), table_name='bank_market_segments')
    op.drop_constraint(op.f('bank_market_segments_lob_id_fkey'), 'bank_market_segments', type_='foreignkey')
    op.create_foreign_key(None, 'bank_market_segments', 'bank_lobs', ['lob_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bank_market_segments', 'updated_at')
    op.add_column('bank_products_services', sa.Column('lob_identifier', sa.String(length=100), nullable=True))
    op.add_column('bank_products_services', sa.Column('sub_lob_identifier', sa.String(length=100), nullable=True))
    op.add_column('bank_products_services', sa.Column('evidence_backed_mapping_statement', sa.Text(), nullable=True))
    op.alter_column('bank_products_services', 'lob_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('idx_prod_serv_bank'), table_name='bank_products_services')
    op.drop_index(op.f('idx_prod_serv_category'), table_name='bank_products_services')
    op.drop_index(op.f('idx_prod_serv_lob'), table_name='bank_products_services')
    op.drop_index(op.f('ix_bank_products_services_product_name'), table_name='bank_products_services')
    op.drop_index(op.f('ix_bank_products_services_service_name'), table_name='bank_products_services')
    op.drop_constraint(op.f('bank_products_services_lob_id_fkey'), 'bank_products_services', type_='foreignkey')
    op.create_foreign_key(None, 'bank_products_services', 'bank_lobs', ['lob_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bank_products_services', 'updated_at')
    op.add_column('bank_technology_initiatives', sa.Column('platform_or_vendor', sa.String(length=255), nullable=True))
    op.add_column('bank_technology_initiatives', sa.Column('associated_lob_sub_lob', sa.String(length=255), nullable=True))
    op.alter_column('bank_technology_initiatives', 'lob_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('bank_technology_initiatives', 'technology_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('bank_technology_initiatives', 'priority_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('bank_technology_initiatives', 'related_technology',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_tech_initiatives_bank'), table_name='bank_technology_initiatives')
    op.drop_index(op.f('idx_tech_initiatives_lob'), table_name='bank_technology_initiatives')
    op.drop_index(op.f('idx_tech_initiatives_tech_cat'), table_name='bank_technology_initiatives')
    op.drop_index(op.f('ix_bank_technology_initiatives_initiative_name'), table_name='bank_technology_initiatives')
    op.drop_index(op.f('ix_bank_technology_initiatives_technology_name'), table_name='bank_technology_initiatives')
    op.drop_constraint(op.f('bank_technology_initiatives_lob_id_fkey'), 'bank_technology_initiatives', type_='foreignkey')
    op.create_foreign_key(None, 'bank_technology_initiatives', 'bank_lobs', ['lob_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bank_technology_initiatives', 'updated_at')
    op.add_column('banks', sa.Column('primary_domain', sa.String(length=255), nullable=True))
    op.add_column('banks', sa.Column('company_url', sa.String(length=500), nullable=True))
    op.add_column('banks', sa.Column('estimated_num_employees', sa.Integer(), nullable=True))
    op.add_column('banks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('banks', sa.Column('retail_location_count', sa.Integer(), nullable=True))
    op.add_column('banks', sa.Column('num_retail_locations', sa.Integer(), nullable=True))
    op.add_column('banks', sa.Column('num_languages', sa.Integer(), nullable=True))
    op.add_column('banks', sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('banks', sa.Column('snippets_loaded', sa.Boolean(), nullable=True))
    op.add_column('banks', sa.Column('owned_by_organization_id', sa.String(length=100), nullable=True))
    op.add_column('banks', sa.Column('organization_revenue', sa.BigInteger(), nullable=True))
    op.add_column('banks', sa.Column('organization_revenue_printed', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('annual_revenue', sa.BigInteger(), nullable=True))
    op.add_column('banks', sa.Column('annual_revenue_printed', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('market_cap', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('total_funding', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('total_funding_printed', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('latest_funding_round_date', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('latest_funding_stage', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('num_suborganizations', sa.Integer(), nullable=True))
    op.add_column('banks', sa.Column('primary_phone', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('banks', sa.Column('sanitized_phone', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('linkedin_uid', sa.String(length=100), nullable=True))
    op.add_column('banks', sa.Column('twitter_url', sa.String(length=500), nullable=True))
    op.add_column('banks', sa.Column('facebook_url', sa.String(length=500), nullable=True))
    op.add_column('banks', sa.Column('angellist_url', sa.String(length=500), nullable=True))
    op.add_column('banks', sa.Column('crunchbase_url', sa.String(length=500), nullable=True))
    op.add_column('banks', sa.Column('raw_address', sa.String(length=500), nullable=True))
    op.add_column('banks', sa.Column('street_address', sa.String(length=500), nullable=True))
    op.add_column('banks', sa.Column('postal_code', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('industries', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('banks', sa.Column('secondary_industries', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('banks', sa.Column('sic_codes', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('banks', sa.Column('naics_codes', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('banks', sa.Column('industry_tag_id', sa.String(length=100), nullable=True))
    op.add_column('banks', sa.Column('industry_tag_hash', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('banks', sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('banks', sa.Column('tech_stack', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('banks', sa.Column('technology_names', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('banks', sa.Column('pain_points', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_index(op.f('idx_banks_name_domain'), table_name='banks')
    op.create_index('idx_banks_domain', 'banks', ['domain'], unique=False)
    op.create_index('idx_banks_keywords', 'banks', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index('idx_banks_naics_codes', 'banks', ['naics_codes'], unique=False, postgresql_using='gin')
    op.create_index('idx_banks_name', 'banks', ['name'], unique=False)
    op.create_index('idx_banks_sic_codes', 'banks', ['sic_codes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_banks_primary_domain'), 'banks', ['primary_domain'], unique=False)
    op.add_column('contacts', sa.Column('contact_id_external', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('full_name', sa.String(length=200), nullable=True))
    op.add_column('contacts', sa.Column('current_title', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('sub_lob_name', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('lob_association', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('organization', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('parent_organization', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('seniority', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('reports_to_name', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('reports_to_title', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('reports_to_path', sa.String(length=500), nullable=True))
    op.add_column('contacts', sa.Column('hierarchy_level', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('geography', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('start_date', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('tenure', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('current_role_validation_date', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('remit', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('responsibilities', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('relationship_evidence', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('classification', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('confidence', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('source_count', sa.Integer(), nullable=True))
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('idx_contacts_bank_lob'), table_name='contacts')
    op.drop_index(op.f('idx_contacts_score_desc'), table_name='contacts')
    op.drop_constraint(op.f('uq_contact_lob_email'), 'contacts', type_='unique')
    op.create_index('idx_contacts_email', 'contacts', ['email'], unique=False)
    op.create_index('idx_contacts_full_name', 'contacts', ['full_name'], unique=False)
    op.create_index('idx_contacts_seniority_tier', 'contacts', ['seniority_tier'], unique=False)
    op.create_index(op.f('ix_contacts_lead_score'), 'contacts', ['lead_score'], unique=False)
    op.add_column('data_source_evidence', sa.Column('highlighted_excerpt', sa.Text(), nullable=True))
    op.add_column('data_source_evidence', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('data_source_evidence', sa.Column('published_time', sa.String(length=50), nullable=True))
    op.add_column('data_source_evidence', sa.Column('last_crawled_time', sa.String(length=50), nullable=True))
    op.add_column('data_source_evidence', sa.Column('duplicate_group_identifier', sa.String(length=100), nullable=True))
    op.alter_column('data_source_evidence', 'bank_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('data_source_evidence', 'favicon',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('data_source_evidence', 'publication_timestamp',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(timezone=True),
               postgresql_using='publication_timestamp::timestamp with time zone',
               existing_nullable=True)
    op.alter_column('data_source_evidence', 'last_crawled_timestamp',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(timezone=True),
               postgresql_using='last_crawled_timestamp::timestamp with time zone',
               existing_nullable=True)
    op.alter_column('data_source_evidence', 'authority_level',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('data_source_evidence', 'claim_identifier',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('data_source_evidence', 'supported_field',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index(op.f('idx_evidence_bank'), table_name='data_source_evidence')
    op.drop_index(op.f('idx_evidence_domain'), table_name='data_source_evidence')
    op.drop_index(op.f('idx_evidence_supported_field'), table_name='data_source_evidence')
    op.drop_index(op.f('ix_data_source_evidence_source_hash'), table_name='data_source_evidence')
    op.add_column('funding_events', sa.Column('funded_at', sa.String(length=50), nullable=True))
    op.add_column('funding_events', sa.Column('round', sa.String(length=100), nullable=True))
    op.add_column('funding_events', sa.Column('money_raised', sa.String(length=50), nullable=True))
    op.drop_index(op.f('idx_funding_events_bank'), table_name='funding_events')
    op.drop_index(op.f('idx_funding_events_type'), table_name='funding_events')
    op.drop_index(op.f('ix_funding_events_funding_event_id'), table_name='funding_events')
    op.add_column('org_hierarchy', sa.Column('hierarchy_level', sa.Integer(), nullable=True))
    op.alter_column('org_hierarchy', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('idx_hierarchy_level'), table_name='org_hierarchy')
    op.drop_index(op.f('idx_hierarchy_manager'), table_name='org_hierarchy')
    op.drop_constraint(op.f('org_hierarchy_contact_id_key'), 'org_hierarchy', type_='unique')
    op.create_index(op.f('ix_org_hierarchy_contact_id'), 'org_hierarchy', ['contact_id'], unique=True)
    op.create_index(op.f('ix_org_hierarchy_manager_id'), 'org_hierarchy', ['manager_id'], unique=False)
    op.add_column('personas', sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('personas', sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('personas', sa.Column('career_trajectory', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('personas', sa.Column('tech_stack', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('personas', sa.Column('operational_pain_points', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('personas', sa.Column('kpis', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('personas', sa.Column('budget_authority', sa.String(length=50), nullable=True))
    op.add_column('personas', sa.Column('decision_authority', sa.String(length=50), nullable=True))
    op.add_column('personas', sa.Column('social_platforms_linkedin', sa.String(length=500), nullable=True))
    op.add_column('personas', sa.Column('social_platforms_twitter', sa.String(length=500), nullable=True))
    op.add_column('personas', sa.Column('social_platforms_portal', sa.String(length=500), nullable=True))
    op.add_column('personas', sa.Column('social_platforms_facebook', sa.String(length=500), nullable=True))
    op.add_column('personas', sa.Column('social_platforms_instagram', sa.String(length=500), nullable=True))
    op.add_column('personas', sa.Column('post_platform', sa.String(length=50), nullable=True))
    op.add_column('personas', sa.Column('post_date', sa.String(length=50), nullable=True))
    op.add_column('personas', sa.Column('post_content', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('post_engagement', sa.String(length=100), nullable=True))
    op.add_column('personas', sa.Column('post_topic_focus', sa.String(length=255), nullable=True))
    op.alter_column('personas', 'professional_interests',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('personas', 'ice_breakers',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('personas', 'objections',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_index(op.f('idx_personas_personal'), table_name='personas', postgresql_ops={'personal_touch': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_personas_tech'), table_name='personas', postgresql_ops={'professional_behavior': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_constraint(op.f('personas_contact_id_key'), 'personas', type_='unique')
    op.create_index('idx_personas_behavior', 'personas', ['professional_behavior'], unique=False, postgresql_using='gin')
    op.create_index('idx_personas_demographics', 'personas', ['demographics'], unique=False, postgresql_using='gin')
    op.create_index('idx_personas_pain_points', 'personas', ['operational_pain_points'], unique=False, postgresql_using='gin')
    op.create_index('idx_personas_personal_touch', 'personas', ['personal_touch'], unique=False, postgresql_using='gin')
    op.create_index('idx_personas_tech_stack', 'personas', ['tech_stack'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_personas_contact_id'), 'personas', ['contact_id'], unique=True)
    op.add_column('tool_execution_logs', sa.Column('provider_id', sa.String(length=100), nullable=True))
    op.add_column('tool_execution_logs', sa.Column('input_query', sa.Text(), nullable=True))
    op.add_column('tool_execution_logs', sa.Column('provider_response_http_status', sa.Integer(), nullable=True))
    op.add_column('tool_execution_logs', sa.Column('cost', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('tool_execution_logs', sa.Column('cost_currency', sa.String(length=20), nullable=True))
    op.add_column('tool_execution_logs', sa.Column('inspect_schema_version_id', sa.String(length=100), nullable=True))
    op.add_column('tool_execution_logs', sa.Column('created_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tool_execution_logs', sa.Column('completed_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tool_execution_logs', 'run_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('tool_execution_logs', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('tool_execution_logs', 'tier_label',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('tool_execution_logs', 'retrieve_response_hint',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('tool_execution_logs', 'find_company_domain_hint',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index(op.f('idx_tool_exec_created'), table_name='tool_execution_logs')
    op.drop_index(op.f('idx_tool_exec_provider_status'), table_name='tool_execution_logs')
    op.drop_index(op.f('ix_tool_execution_logs_provider'), table_name='tool_execution_logs')
    op.drop_index(op.f('ix_tool_execution_logs_status'), table_name='tool_execution_logs')
    op.drop_index(op.f('ix_tool_execution_logs_run_id'), table_name='tool_execution_logs')
    op.create_index(op.f('ix_tool_execution_logs_run_id'), 'tool_execution_logs', ['run_id'], unique=False)
    op.create_index('idx_tool_logs_provider_endpoint', 'tool_execution_logs', ['provider', 'endpoint'], unique=False)
    op.create_index('idx_tool_logs_run_id', 'tool_execution_logs', ['run_id'], unique=False)
    op.drop_column('tool_execution_logs', 'inspect_schema_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_execution_logs', sa.Column('inspect_schema_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index('idx_tool_logs_run_id', table_name='tool_execution_logs')
    op.drop_index('idx_tool_logs_provider_endpoint', table_name='tool_execution_logs')
    op.drop_index(op.f('ix_tool_execution_logs_run_id'), table_name='tool_execution_logs')
    op.create_index(op.f('ix_tool_execution_logs_run_id'), 'tool_execution_logs', ['run_id'], unique=True)
    op.create_index(op.f('ix_tool_execution_logs_status'), 'tool_execution_logs', ['status'], unique=False)
    op.create_index(op.f('ix_tool_execution_logs_provider'), 'tool_execution_logs', ['provider'], unique=False)
    op.create_index(op.f('idx_tool_exec_provider_status'), 'tool_execution_logs', ['provider', 'status'], unique=False)
    op.create_index(op.f('idx_tool_exec_created'), 'tool_execution_logs', ['created_at'], unique=False)
    op.alter_column('tool_execution_logs', 'find_company_domain_hint',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tool_execution_logs', 'retrieve_response_hint',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tool_execution_logs', 'tier_label',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('tool_execution_logs', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('tool_execution_logs', 'run_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('tool_execution_logs', 'completed_timestamp')
    op.drop_column('tool_execution_logs', 'created_timestamp')
    op.drop_column('tool_execution_logs', 'inspect_schema_version_id')
    op.drop_column('tool_execution_logs', 'cost_currency')
    op.drop_column('tool_execution_logs', 'cost')
    op.drop_column('tool_execution_logs', 'provider_response_http_status')
    op.drop_column('tool_execution_logs', 'input_query')
    op.drop_column('tool_execution_logs', 'provider_id')
    op.drop_index(op.f('ix_personas_contact_id'), table_name='personas')
    op.drop_index('idx_personas_tech_stack', table_name='personas', postgresql_using='gin')
    op.drop_index('idx_personas_personal_touch', table_name='personas', postgresql_using='gin')
    op.drop_index('idx_personas_pain_points', table_name='personas', postgresql_using='gin')
    op.drop_index('idx_personas_demographics', table_name='personas', postgresql_using='gin')
    op.drop_index('idx_personas_behavior', table_name='personas', postgresql_using='gin')
    op.create_unique_constraint(op.f('personas_contact_id_key'), 'personas', ['contact_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_personas_tech'), 'personas', ['professional_behavior'], unique=False, postgresql_ops={'professional_behavior': 'jsonb_path_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_personas_personal'), 'personas', ['personal_touch'], unique=False, postgresql_ops={'personal_touch': 'jsonb_path_ops'}, postgresql_using='gin')
    op.alter_column('personas', 'objections',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('personas', 'ice_breakers',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('personas', 'professional_interests',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.drop_column('personas', 'post_topic_focus')
    op.drop_column('personas', 'post_engagement')
    op.drop_column('personas', 'post_content')
    op.drop_column('personas', 'post_date')
    op.drop_column('personas', 'post_platform')
    op.drop_column('personas', 'social_platforms_instagram')
    op.drop_column('personas', 'social_platforms_facebook')
    op.drop_column('personas', 'social_platforms_portal')
    op.drop_column('personas', 'social_platforms_twitter')
    op.drop_column('personas', 'social_platforms_linkedin')
    op.drop_column('personas', 'decision_authority')
    op.drop_column('personas', 'budget_authority')
    op.drop_column('personas', 'kpis')
    op.drop_column('personas', 'operational_pain_points')
    op.drop_column('personas', 'tech_stack')
    op.drop_column('personas', 'career_trajectory')
    op.drop_column('personas', 'experience')
    op.drop_column('personas', 'education')
    op.drop_index(op.f('ix_org_hierarchy_manager_id'), table_name='org_hierarchy')
    op.drop_index(op.f('ix_org_hierarchy_contact_id'), table_name='org_hierarchy')
    op.create_unique_constraint(op.f('org_hierarchy_contact_id_key'), 'org_hierarchy', ['contact_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_hierarchy_manager'), 'org_hierarchy', ['manager_id'], unique=False)
    op.create_index(op.f('idx_hierarchy_level'), 'org_hierarchy', ['level'], unique=False)
    op.alter_column('org_hierarchy', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('org_hierarchy', 'hierarchy_level')
    op.create_index(op.f('ix_funding_events_funding_event_id'), 'funding_events', ['funding_event_id'], unique=False)
    op.create_index(op.f('idx_funding_events_type'), 'funding_events', ['type'], unique=False)
    op.create_index(op.f('idx_funding_events_bank'), 'funding_events', ['bank_id'], unique=False)
    op.drop_column('funding_events', 'money_raised')
    op.drop_column('funding_events', 'round')
    op.drop_column('funding_events', 'funded_at')
    op.create_index(op.f('ix_data_source_evidence_source_hash'), 'data_source_evidence', ['source_hash'], unique=False)
    op.create_index(op.f('idx_evidence_supported_field'), 'data_source_evidence', ['supported_field'], unique=False)
    op.create_index(op.f('idx_evidence_domain'), 'data_source_evidence', ['domain'], unique=False)
    op.create_index(op.f('idx_evidence_bank'), 'data_source_evidence', ['bank_id'], unique=False)
    op.alter_column('data_source_evidence', 'supported_field',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('data_source_evidence', 'claim_identifier',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('data_source_evidence', 'authority_level',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('data_source_evidence', 'last_crawled_timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('data_source_evidence', 'publication_timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('data_source_evidence', 'favicon',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('data_source_evidence', 'bank_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('data_source_evidence', 'duplicate_group_identifier')
    op.drop_column('data_source_evidence', 'last_crawled_time')
    op.drop_column('data_source_evidence', 'published_time')
    op.drop_column('data_source_evidence', 'content')
    op.drop_column('data_source_evidence', 'highlighted_excerpt')
    op.drop_index(op.f('ix_contacts_lead_score'), table_name='contacts')
    op.drop_index('idx_contacts_seniority_tier', table_name='contacts')
    op.drop_index('idx_contacts_full_name', table_name='contacts')
    op.drop_index('idx_contacts_email', table_name='contacts')
    op.create_unique_constraint(op.f('uq_contact_lob_email'), 'contacts', ['lob_id', 'email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_contacts_score_desc'), 'contacts', [sa.literal_column('lead_score DESC')], unique=False)
    op.create_index(op.f('idx_contacts_bank_lob'), 'contacts', ['bank_id', 'lob_id'], unique=False)
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('contacts', 'source_count')
    op.drop_column('contacts', 'confidence')
    op.drop_column('contacts', 'classification')
    op.drop_column('contacts', 'relationship_evidence')
    op.drop_column('contacts', 'responsibilities')
    op.drop_column('contacts', 'remit')
    op.drop_column('contacts', 'current_role_validation_date')
    op.drop_column('contacts', 'tenure')
    op.drop_column('contacts', 'start_date')
    op.drop_column('contacts', 'geography')
    op.drop_column('contacts', 'hierarchy_level')
    op.drop_column('contacts', 'reports_to_path')
    op.drop_column('contacts', 'reports_to_title')
    op.drop_column('contacts', 'reports_to_name')
    op.drop_column('contacts', 'seniority')
    op.drop_column('contacts', 'parent_organization')
    op.drop_column('contacts', 'organization')
    op.drop_column('contacts', 'lob_association')
    op.drop_column('contacts', 'sub_lob_name')
    op.drop_column('contacts', 'current_title')
    op.drop_column('contacts', 'full_name')
    op.drop_column('contacts', 'contact_email')
    op.drop_column('contacts', 'contact_id_external')
    op.drop_index(op.f('ix_banks_primary_domain'), table_name='banks')
    op.drop_index('idx_banks_sic_codes', table_name='banks', postgresql_using='gin')
    op.drop_index('idx_banks_name', table_name='banks')
    op.drop_index('idx_banks_naics_codes', table_name='banks', postgresql_using='gin')
    op.drop_index('idx_banks_keywords', table_name='banks', postgresql_using='gin')
    op.drop_index('idx_banks_domain', table_name='banks')
    op.create_index(op.f('idx_banks_name_domain'), 'banks', ['name', 'domain'], unique=False)
    op.drop_column('banks', 'pain_points')
    op.drop_column('banks', 'technology_names')
    op.drop_column('banks', 'tech_stack')
    op.drop_column('banks', 'keywords')
    op.drop_column('banks', 'industry_tag_hash')
    op.drop_column('banks', 'industry_tag_id')
    op.drop_column('banks', 'naics_codes')
    op.drop_column('banks', 'sic_codes')
    op.drop_column('banks', 'secondary_industries')
    op.drop_column('banks', 'industries')
    op.drop_column('banks', 'postal_code')
    op.drop_column('banks', 'street_address')
    op.drop_column('banks', 'raw_address')
    op.drop_column('banks', 'crunchbase_url')
    op.drop_column('banks', 'angellist_url')
    op.drop_column('banks', 'facebook_url')
    op.drop_column('banks', 'twitter_url')
    op.drop_column('banks', 'linkedin_uid')
    op.drop_column('banks', 'sanitized_phone')
    op.drop_column('banks', 'primary_phone')
    op.drop_column('banks', 'num_suborganizations')
    op.drop_column('banks', 'latest_funding_stage')
    op.drop_column('banks', 'latest_funding_round_date')
    op.drop_column('banks', 'total_funding_printed')
    op.drop_column('banks', 'total_funding')
    op.drop_column('banks', 'market_cap')
    op.drop_column('banks', 'annual_revenue_printed')
    op.drop_column('banks', 'annual_revenue')
    op.drop_column('banks', 'organization_revenue_printed')
    op.drop_column('banks', 'organization_revenue')
    op.drop_column('banks', 'owned_by_organization_id')
    op.drop_column('banks', 'snippets_loaded')
    op.drop_column('banks', 'languages')
    op.drop_column('banks', 'num_languages')
    op.drop_column('banks', 'num_retail_locations')
    op.drop_column('banks', 'retail_location_count')
    op.drop_column('banks', 'description')
    op.drop_column('banks', 'estimated_num_employees')
    op.drop_column('banks', 'company_url')
    op.drop_column('banks', 'primary_domain')
    op.add_column('bank_technology_initiatives', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bank_technology_initiatives', type_='foreignkey')
    op.create_foreign_key(op.f('bank_technology_initiatives_lob_id_fkey'), 'bank_technology_initiatives', 'bank_lobs', ['lob_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_bank_technology_initiatives_technology_name'), 'bank_technology_initiatives', ['technology_name'], unique=False)
    op.create_index(op.f('ix_bank_technology_initiatives_initiative_name'), 'bank_technology_initiatives', ['initiative_name'], unique=False)
    op.create_index(op.f('idx_tech_initiatives_tech_cat'), 'bank_technology_initiatives', ['technology_category'], unique=False)
    op.create_index(op.f('idx_tech_initiatives_lob'), 'bank_technology_initiatives', ['lob_id'], unique=False)
    op.create_index(op.f('idx_tech_initiatives_bank'), 'bank_technology_initiatives', ['bank_id'], unique=False)
    op.alter_column('bank_technology_initiatives', 'related_technology',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bank_technology_initiatives', 'priority_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('bank_technology_initiatives', 'technology_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('bank_technology_initiatives', 'lob_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('bank_technology_initiatives', 'associated_lob_sub_lob')
    op.drop_column('bank_technology_initiatives', 'platform_or_vendor')
    op.add_column('bank_products_services', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bank_products_services', type_='foreignkey')
    op.create_foreign_key(op.f('bank_products_services_lob_id_fkey'), 'bank_products_services', 'bank_lobs', ['lob_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_bank_products_services_service_name'), 'bank_products_services', ['service_name'], unique=False)
    op.create_index(op.f('ix_bank_products_services_product_name'), 'bank_products_services', ['product_name'], unique=False)
    op.create_index(op.f('idx_prod_serv_lob'), 'bank_products_services', ['lob_id'], unique=False)
    op.create_index(op.f('idx_prod_serv_category'), 'bank_products_services', ['product_category', 'service_category'], unique=False)
    op.create_index(op.f('idx_prod_serv_bank'), 'bank_products_services', ['bank_id'], unique=False)
    op.alter_column('bank_products_services', 'lob_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('bank_products_services', 'evidence_backed_mapping_statement')
    op.drop_column('bank_products_services', 'sub_lob_identifier')
    op.drop_column('bank_products_services', 'lob_identifier')
    op.add_column('bank_market_segments', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bank_market_segments', type_='foreignkey')
    op.create_foreign_key(op.f('bank_market_segments_lob_id_fkey'), 'bank_market_segments', 'bank_lobs', ['lob_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_bank_market_segments_market_name'), 'bank_market_segments', ['market_name'], unique=False)
    op.create_index(op.f('idx_market_segments_lob'), 'bank_market_segments', ['lob_id'], unique=False)
    op.create_index(op.f('idx_market_segments_client_type'), 'bank_market_segments', ['customer_type', 'client_segment'], unique=False)
    op.create_index(op.f('idx_market_segments_bank'), 'bank_market_segments', ['bank_id'], unique=False)
    op.alter_column('bank_market_segments', 'evidence_url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('bank_market_segments', 'served_geography',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('bank_market_segments', 'served_segment',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('bank_market_segments', 'lob_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('bank_market_segments', 'parent_lob_sub_lob')
    op.drop_index('idx_bank_lobs_name', table_name='bank_lobs')
    op.drop_index('idx_bank_lobs_hierarchy_path', table_name='bank_lobs')
    op.create_index(op.f('idx_lob_bank_parent'), 'bank_lobs', ['bank_id', 'parent_lob_id'], unique=False)
    op.drop_column('bank_lobs', 'last_crawled_time')
    op.drop_column('bank_lobs', 'published_time')
    op.drop_column('bank_lobs', 'crawl_timestamp')
    op.drop_column('bank_lobs', 'publication_timestamp')
    op.drop_column('bank_lobs', 'content')
    op.drop_column('bank_lobs', 'full_content')
    op.drop_column('bank_lobs', 'excerpt')
    op.drop_column('bank_lobs', 'highlighted_excerpt')
    op.drop_column('bank_lobs', 'source_url')
    op.drop_column('bank_lobs', 'source_title')
    op.drop_column('bank_lobs', 'authoritative_source_flag')
    op.drop_column('bank_lobs', 'evidence_count')
    op.drop_column('bank_lobs', 'validation_status')
    op.drop_column('bank_lobs', 'classification_type')
    op.drop_column('bank_lobs', 'classification')
    op.drop_column('bank_lobs', 'supporting_statement')
    op.drop_column('bank_lobs', 'detailed_description')
    op.drop_column('bank_lobs', 'short_description')
    op.drop_column('bank_lobs', 'key_platforms')
    op.drop_column('bank_lobs', 'confidence_level')
    op.drop_column('bank_lobs', 'division_leader')
    op.drop_column('bank_lobs', 'responsibilities')
    op.drop_column('bank_lobs', 'functions')
    op.drop_column('bank_lobs', 'industries')
    op.drop_column('bank_lobs', 'estimated_num_employees')
    op.drop_column('bank_lobs', 'relationship_description')
    op.drop_column('bank_lobs', 'relationship_type')
    op.drop_column('bank_lobs', 'parent_child_relationship')
    op.drop_column('bank_lobs', 'child_node')
    op.drop_column('bank_lobs', 'child_entity')
    op.drop_column('bank_lobs', 'parent_entity')
    op.drop_column('bank_lobs', 'node_type')
    op.drop_column('bank_lobs', 'node_name')
    op.drop_column('bank_lobs', 'business_unit_name')
    op.drop_column('bank_lobs', 'normalized_name')
    op.drop_column('bank_lobs', 'entity_name')
    # ### end Alembic commands ###
