"""add_publicly_traded_and_alexa_ranking

Revision ID: e1d428444c88
Revises: b43080540cfb
Create Date: 2026-08-17 14:40:56.347678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1d428444c88'
down_revision: Union[str, Sequence[str], None] = 'b43080540cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banks', sa.Column('publicly_traded_symbol', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('publicly_traded_exchange', sa.String(length=50), nullable=True))
    op.add_column('banks', sa.Column('alexa_ranking', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banks', 'alexa_ranking')
    op.drop_column('banks', 'publicly_traded_exchange')
    op.drop_column('banks', 'publicly_traded_symbol')
    # ### end Alembic commands ###
