"""initial_schema

Revision ID: e35b2f488f24
Revises: 
Create Date: 2026-08-11 18:36:34.682384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e35b2f488f24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('revenue_range', sa.String(length=50), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('headquarters', sa.String(length=255), nullable=True),
    sa.Column('tech_stack', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('pain_points', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('annual_reports', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_banks_industry', 'banks', ['industry'], unique=False)
    op.create_index('idx_banks_pain_points', 'banks', ['pain_points'], unique=False, postgresql_using='gin')
    op.create_index('idx_banks_tech_stack', 'banks', ['tech_stack'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_banks_domain'), 'banks', ['domain'], unique=True)
    op.create_index(op.f('ix_banks_name'), 'banks', ['name'], unique=False)
    op.create_table('bank_lobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=True),
    sa.Column('annual_budget', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('tech_stack', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('pain_points', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('priorities', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lob_bank', 'bank_lobs', ['bank_id'], unique=False)
    op.create_index('idx_lob_type', 'bank_lobs', ['type'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lob_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('seniority', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('is_decision_maker', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lob_id'], ['bank_lobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lob_id', 'email', name='uq_contact_lob_email')
    )
    op.create_index('idx_contacts_email', 'contacts', ['email'], unique=False)
    op.create_index('idx_contacts_lob', 'contacts', ['lob_id'], unique=False)
    op.create_index('idx_contacts_score', 'contacts', ['lead_score'], unique=False, postgresql_ops={'lead_score': 'DESC'})
    op.create_index('idx_contacts_seniority', 'contacts', ['seniority'], unique=False)
    op.create_index('idx_contacts_status', 'contacts', ['status'], unique=False)
    op.create_table('org_hierarchy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('reports_to_path', sa.String(length=500), nullable=True),
    sa.Column('influence_score', sa.Integer(), nullable=True),
    sa.Column('decision_authority', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id')
    )
    op.create_index('idx_hierarchy_level', 'org_hierarchy', ['level'], unique=False)
    op.create_index('idx_hierarchy_manager', 'org_hierarchy', ['manager_id'], unique=False)
    op.create_table('personas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('demographics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('professional_behavior', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('personal_touch', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ice_breakers', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('last_enriched', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id')
    )
    op.create_index('idx_personas_tech', 'personas', ['professional_behavior'], unique=False, postgresql_using='gin', postgresql_ops={'professional_behavior': 'jsonb_path_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_personas_tech', table_name='personas', postgresql_using='gin', postgresql_ops={'professional_behavior': 'jsonb_path_ops'})
    op.drop_table('personas')
    op.drop_index('idx_hierarchy_manager', table_name='org_hierarchy')
    op.drop_index('idx_hierarchy_level', table_name='org_hierarchy')
    op.drop_table('org_hierarchy')
    op.drop_index('idx_contacts_status', table_name='contacts')
    op.drop_index('idx_contacts_seniority', table_name='contacts')
    op.drop_index('idx_contacts_score', table_name='contacts', postgresql_ops={'lead_score': 'DESC'})
    op.drop_index('idx_contacts_lob', table_name='contacts')
    op.drop_index('idx_contacts_email', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('idx_lob_type', table_name='bank_lobs')
    op.drop_index('idx_lob_bank', table_name='bank_lobs')
    op.drop_table('bank_lobs')
    op.drop_index(op.f('ix_banks_name'), table_name='banks')
    op.drop_index(op.f('ix_banks_domain'), table_name='banks')
    op.drop_index('idx_banks_tech_stack', table_name='banks', postgresql_using='gin')
    op.drop_index('idx_banks_pain_points', table_name='banks', postgresql_using='gin')
    op.drop_index('idx_banks_industry', table_name='banks')
    op.drop_table('banks')
    # ### end Alembic commands ###
